/**
 * @description BenefitsAffiliatesAccount_Test contains tests for the BenefitsAffiliatesAccount class.
 */
@IsTest
public with sharing class BenefitsAffiliatesAccount_Test {
    /**
	 * @description method performs a test on .
	 */
	@IsTest
	public static void test_method() {
		
		// Setup Data
		
		Test.startTest();
		
		// Run Test
		
		Test.stopTest();
		
		// Asserts
		// Assert.isTrue(false, 'explaination');
	}
}